### ISSUE TITLE
C++11 compilation warning: use of the 'deprecated' attribute is a C++14 extension

### ISSUE THREAD

**Issue by mloskot** [boostorg/mp11#31]
Compilation of a MP11-enabled program in C++11 mode with clang spits the following warning

```
./boost/mp11/utility.hpp:223:47: warning: use of the 'deprecated' attribute is a C++14 extension [-Wc++14-extensions]
template<class Q, class... T> using mp_invoke BOOST_MP11_DEPRECATED("please use mp_invoke_q") = mp_invoke_q<Q, T...>;
                                              ^
./boost/mp11/detail/config.hpp:136:41: note: expanded from macro 'BOOST_MP11_DEPRECATED'
#   define BOOST_MP11_DEPRECATED(msg) [[deprecated(msg)]]
                                        ^
```

For example, https://travis-ci.org/mloskot/gil/jobs/509457000

**Comment by pdimov** [comment]
You wanted Clang to be `-pedantic`, you got pedantry.

**Comment by mloskot** [comment]
I see. I've failed to make the connection. Thanks.

**Comment by pdimov** [comment]
I didn't know about it either. I also didn't know that `warnings=all` set `-pedantic` and thought that Clang is stupid to issue this warning in `-Wall` or even `-Wextra`. Well, it turned out that Clang wasn't stupid after all. :-)

There's work being done on `b2` to fix this: https://github.com/boostorg/build/commit/6611aebf3c799216d34138166b5b5923d072a8f4

**Comment by mloskot** [comment]
Days of me acknowledging (my) stupidity of `-pedantic` or explicit `-W` flags in `Jamfile` are close.
